# Site settings
title: Praneeth's personal site
description: >- # this means to ignore newlines until "baseurl:"
  Hello! My name is Bedapudi Praneeth and I currently work as a Sr. NLP Engineer at DeepAffects.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: bedapudi6788/portfolYOU


# Build settings
markdown: kramdown
remote_theme: bedapudi6788/portfolYOU

# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Bedapudi Praneeth
  image    : /images/profile_pic.png
  email    : praneeth@bpraneeth.com
  github   : bedapudi6788
  linkedin : bedapudi-praneeth
  medium : praneethbedapudi


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
